# Generated by Django 4.1.1 on 2022-09-26 05:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EqptType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Наименование типа"
                    ),
                ),
                (
                    "mask",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[NAaXZ]+$")
                            )
                        ],
                        verbose_name="Маска серийного номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оборудования",
            },
        ),
        migrations.CreateModel(
            name="Eqpt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Наименование типа"
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "eqpt_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eqpts",
                        to="main.eqpttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
            },
        ),
    ]
