# Generated by Django 4.1.1 on 2022-09-26 05:21

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eqpt",
            name="serial_number",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Наименование типа"
            ),
        ),
        migrations.AlterField(
            model_name="eqpttype",
            name="mask",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(re.compile("^[NAaXZ]+$"))
                ],
                verbose_name="Маска серийного номера",
            ),
        ),
        migrations.AlterField(
            model_name="eqpttype",
            name="name",
            field=models.CharField(
                max_length=252, unique=True, verbose_name="Наименование типа"
            ),
        ),
    ]
