# Generated by Django 4.1.1 on 2022-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_eqpt_serial_number_alter_eqpttype_mask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eqpt",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="eqpt",
            name="serial_number",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Серийный номер"
            ),
        ),
    ]
